/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    FeatureItem: typeof import('./components/FeatureItem.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    IntlSearchAlert: typeof import('./components/IntlSearchAlert.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    LocaleSelect: typeof import('./components/LocaleSelect.vue')['default']
    NativeSelect: typeof import('./components/ui/native-select/NativeSelect.vue')['default']
    NativeSelectOptGroup: typeof import('./components/ui/native-select/NativeSelectOptGroup.vue')['default']
    NativeSelectOption: typeof import('./components/ui/native-select/NativeSelectOption.vue')['default']
    PopupHeader: typeof import('./components/PopupHeader.vue')['default']
    Spinner: typeof import('./components/ui/spinner/Spinner.vue')['default']
    Switch: typeof import('./components/ui/switch/Switch.vue')['default']
  }
}
